# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('category_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60)),
                ('event_image', models.ImageField(null=True, upload_to='pics/')),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=60)),
                ('number_of_tickets', models.IntegerField()),
                ('event_type', models.CharField(max_length=60)),
                ('event_topic', models.CharField(max_length=60)),
            ],
        ),
    ]
