# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('category_image', models.ImageField(upload_to='category-images')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('event_status', models.CharField(choices=[('F', 'FREE'), ('P', 'PAID')], max_length=2, null=True)),
                ('event_charges', models.CharField(max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid amount', regex='^(\\d{1,5})$')])),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=60)),
                ('number_of_tickets', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid number', regex='^(\\d{1,5})$')])),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_created_on', models.DateTimeField(auto_now_add=True)),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
            options={
                'ordering': ['-event_created_on'],
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ticket_no', models.CharField(max_length=50, unique=True)),
                ('event_ticket_taken', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(blank=True, max_length=80, null=True)),
                ('profile_location', models.CharField(max_length=254, null=True)),
                ('profile_subscribed', models.BooleanField(default=False)),
                ('profile_interest', models.ManyToManyField(null=True, related_name='interests', to='app.Category')),
                ('profile_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_idf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='ID number must be numeric and eight characters', regex='^(\\d{7}|\\d{8})$')], verbose_name='Identification Number')),
                ('profile_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Incorrect Phone Number', regex='^(0+[7]{1}[0-9]{8})$')], verbose_name='Phone Number')),
                ('number_of_tickets', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid number', regex='^(\\d{1,5})$')])),
                ('ticket_confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='eventticket',
            name='event_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TicketBooking'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
