# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=80)),
                ('profile_email', models.CharField(max_length=100)),
                ('profile_interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='app.Category')),
                ('profile_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
