# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180616_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_location',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
