# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=60)),
                ('event_image', models.ImageField(null=True, upload_to='event-images/')),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(max_length=60)),
                ('number_of_tickets', models.IntegerField()),
                ('event_type', models.CharField(max_length=60)),
                ('event_topic', models.CharField(max_length=255)),
            ],
        ),
    ]
