# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180616_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Paid')], default='F', max_length=2),
            preserve_default=False,
        ),
    ]
