# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 06:04
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
