# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 13:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180617_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_idf', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='ID number must be numeric and eight characters', regex='^(\\d{7}|\\d{8})$')], verbose_name='Identification Number')),
                ('profile_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Incorrect Phone Number', regex='^(0+[7]{1}[0-9]{8})$')], verbose_name='Phone Number')),
                ('number_of_tickets', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid number', regex='^(\\d{1,5})$')])),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('F', 'FREE'), ('P', 'PAID')], max_length=2),
        ),
    ]
