# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180617_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_id',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
            preserve_default=False,
        ),
    ]
