# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ticket_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
