# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180619_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
    ]
