# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_category_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
