# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_profile_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('F', 'FREE'), ('P', 'PAID')], max_length=2, null=True),
        ),
    ]
