# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180627_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
